### ISSUE TITLE
error: no matching constructor for initialization of 'RkWidget'

### ISSUE THREAD

**Issue by yurivict** [iurie-sw/redkite#27] opened 2020-08-04 18:37 UTC
```
/usr/ports/x11-toolkits/redkite/work/redkite-1.0.1-2-g1e62086/src/RkButton.cpp:30:11: error: no matching constructor for initialization of 'RkWidget'
        : RkWidget(parent, std::make_unique<RkButtonImpl>(this, parent))
          ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

FreeBSD 12.1
clang-9

**Comment by iurienistor** [comment] 2020-08-05 08:21
Hi, thank you. I'll take a look into this next week.

**Comment by iurienistor** [comment] 2020-08-09 16:18
It is strange that I can't reproduce even with clang 10 (all tested on Ubuntu only).

**Comment by iurienistor** [comment] 2020-08-09 16:24
I've made an update of the release, please try if you can reproduce the problem. Even thought I don't see why there should be this compile error.

**Comment by iurienistor** [comment] 2020-08-12 10:56
Ok, I am closing this issue. If it will be reproduced, than I'll reopen it. Thank you!

**Closed by iurienistor** 2020-08-12 10:56 UTC
Labels: to confirm
